version: "3.4"
services:
  db:
    image: postgres:13.4
    container_name: db
    hostname: db
    restart: always
    # To be removed. Only for debugging
    ports:
      - "25432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  bot:
    build: .
    container_name: bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./media/image:/app/image
      - ./media/audio:/app/audio
    depends_on:
      - db

volumes:
  db-data: